alter table OCAT_INTERVIEW add constraint FK_OCAT_INTERVIEW_ON_INTERVIEWER foreign key (INTERVIEWER_ID) references SEC_USER(ID);
create index IDX_OCAT_INTERVIEW_ON_INTERVIEWER on OCAT_INTERVIEW (INTERVIEWER_ID);
