alter table OCAT_QUESTIONNAIRE add constraint FK_OCAT_QUESTIONNAIRE_ON_PARENT foreign key (PARENT_ID) references OCAT_QUESTIONNAIRE(ID);
create index IDX_OCAT_QUESTIONNAIRE_ON_PARENT on OCAT_QUESTIONNAIRE (PARENT_ID);
