alter table OCAT_INTERVIEW add constraint FK_OCAT_INTERVIEW_ON_CLIENT foreign key (CLIENT_ID) references OCAT_CLIENT(ID);
alter table OCAT_INTERVIEW add constraint FK_OCAT_INTERVIEW_ON_RELATED_CASE foreign key (RELATED_CASE_ID) references OCAT_CW_CASE(ID);
create index IDX_OCAT_INTERVIEW_ON_CLIENT on OCAT_INTERVIEW (CLIENT_ID);
create index IDX_OCAT_INTERVIEW_ON_RELATED_CASE on OCAT_INTERVIEW (RELATED_CASE_ID);
