alter table OCAT_INTERVIEW_CONFIG add constraint FK_OCAT_INTERVIEW_CONFIG_ON_PARENT foreign key (PARENT_ID) references OCAT_INTERVIEW_CONFIG(ID);
create index IDX_OCAT_INTERVIEW_CONFIG_ON_PARENT on OCAT_INTERVIEW_CONFIG (PARENT_ID);
