alter table OCAT_INTERVIEW_RESPONSE add constraint FK_OCAT_INTERVIEW_RESPONSE_ON_QUESTION foreign key (QUESTION_ID) references OCAT_QUESTIONNAIRE(ID);
alter table OCAT_INTERVIEW_RESPONSE add constraint FK_OCAT_INTERVIEW_RESPONSE_ON_INTERVIEW foreign key (INTERVIEW_ID) references OCAT_INTERVIEW(ID);
create index IDX_OCAT_INTERVIEW_RESPONSE_ON_QUESTION on OCAT_INTERVIEW_RESPONSE (QUESTION_ID);
create index IDX_OCAT_INTERVIEW_RESPONSE_ON_INTERVIEW on OCAT_INTERVIEW_RESPONSE (INTERVIEW_ID);
